# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ChallengeMOIA' do
  use_frameworks!

  pod 'Swinject', '~> 2.8.1'
  pod 'GoogleMaps', '6.1.1'
  pod 'Alamofire', '~> 4.8'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end